#!/bin/bash

echo "Installing Node v4.0.0 via NVM";
git clone --depth 1 https://github.com/creationix/nvm.git ~/.nvm;
source ~/.nvm/nvm.sh;
nvm install v4.0.0;
nvm alias default v4.0.0;
echo "[ -s $HOME/.nvm/nvm.sh ] && . $HOME/.nvm/nvm.sh # This loads NVM" >> /home/$USER/.profile
